### ISSUE TITLE
Error while activity adding if date not picked

### ISSUE THREAD

**Issue by uskudarli** [TalatCikikci/Fall2016Swe573_HealthTracker#38]
If while adding a date is not picked, the error below is retrieved
![image](https://cloud.githubusercontent.com/assets/1347035/21621096/2f74e7e6-d200-11e6-909d-9a355da28734.png)

**Comment by TalatCikikci** [comment]
Issue has been recreated in the test environment. Fix in progress.

A similar issue is also discovered in "Add Food" process. It can be tracked through #41 .

**Comment by TalatCikikci** [comment]
Added validation for the date field. Issue is fixed.
