### ISSUE TITLE
No calorie is shown for an activity

### ISSUE THREAD

**Issue by uskudarli** [TalatCikikci/Fall2016Swe573_HealthTracker#39]
![image](https://cloud.githubusercontent.com/assets/1347035/21621255/cfa07924-d200-11e6-9b24-8c3b5be00768.png)

**Comment by TalatCikikci** [comment]
Issue has been recreated in the test environment. Fix in progress.

**Comment by TalatCikikci** [comment]
Calories are now displayed properly. The issue is fixed.
