### ISSUE TITLE
No calorie is shown for consumption

### ISSUE THREAD

**Issue by uskudarli** [TalatCikikci/Fall2016Swe573_HealthTracker#40]
![image](https://cloud.githubusercontent.com/assets/1347035/21621281/fb98e2e6-d200-11e6-9b0f-658446017a45.png)

**Comment by TalatCikikci** [comment]
Issue has been recreated in the test environment. Fix in progress.

**Comment by TalatCikikci** [comment]
Calories are now shown properly. Also the units of amount consumed is added for clarity.

This issue is fixed.
